/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;


import static Interfaz.Inicio.titulos;
//import java.io.BufferedReader;
//import java.io.FileReader;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import metromendeley.Menu;
import metromendeley.Resumen;
import javax.swing.*;
//import metromendeley.HashTable;
import metromendeley.Lista;
//import metromendeley.Lista;
import metromendeley.Nodo;

/**
 *
 * @author KelvinCi
 */
public class AnalizarResumeness extends javax.swing.JFrame {

    DefaultListModel modelo;

    /**
     * Creates new form AnalizarResumeness
     */
    public AnalizarResumeness() {
        initComponents();
        modelo = new DefaultListModel();
        jList2.setModel(modelo);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pizarra = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        pizarra1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, -1, -1));

        jButton1.setText("Mostrar Resumenes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 158, -1, -1));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 6, 106, -1));

        jButton2.setText("Mostrar Frecuencia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 187, -1, -1));

        pizarra.setColumns(20);
        pizarra.setRows(5);
        jScrollPane1.setViewportView(pizarra);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 250, 274));

        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 331, -1, -1));

        pizarra1.setColumns(20);
        pizarra1.setRows(5);
        jScrollPane3.setViewportView(pizarra1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 274));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void WordCounter(String titulo) {

        String text = Inicio.tabla.getResumen(titulo).getCuerpo();
        Resumen rsm = Inicio.tabla.getResumen(titulo);

        // Palabras clave a buscar
        Lista<String> keywordss = Inicio.palabrasClavesBD;
        String[] keywords = new String[keywordss.getLenght()];
        Nodo<String> aux = Inicio.palabrasClavesBD.getFirst();
        for (int i = 0; i < keywordss.getLenght(); i++) {
            keywords[i] = aux.getValor();
            aux = aux.getSiguiente();
        }
        //String[] keyword = {"fundaciones directas", "AutoCAD", "complemento", "C#"};

        // Arreglo para contar las apariciones
        int[] keywordCounts = new int[keywords.length];

        // Contar las apariciones de cada palabra clave
        for (int i = 0; i < keywords.length; i++) {
            keywordCounts[i] = countOccurrences(text, keywords[i]);
        }

        // Mostrar los resultados
        String cadena = "";
        cadena += rsm.getTitulo() + "\n" + "Autores: " + rsm.getAutores().toString() + "\n\n";

        for (int i = 0; i < keywords.length; i++) {
            cadena += capitalize(keywords[i]) + " : " + keywordCounts[i] + " veces. \n";
            pizarra.setText(cadena);
            //System.out.println("La palabra '" + keywords[i] + "' aparece " + keywordCounts[i] + " veces.");
        }
    }

    public String capitalize(String input) {
        if (input == null || input.isEmpty()) {
            return input;
        }
        return input.substring(0, 1).toUpperCase() + input.substring(1);
    }

    // Método para contar las apariciones de una palabra clave en el texto
    private static int countOccurrences(String text, String keyword) {
        int count = 0;
        int index = 0;

        while ((index = text.indexOf(keyword, index)) != -1) {
            count++;
            index += keyword.length();
        }

        return count;
    }

    /*
    public int Frecuencia(String PalabraClave,int indice){
        int frecuencia=0;
        
        Resumen resumen=Inicio.tabla.getResumenAt(indice);
        for (int i = 0; i < resumen.getCuerpo().length(); i++) {
            Pa
            if(resumen.getPalabras_clave().contains())
        }
        return frecuencia;
    }*/
    /*public void Cargar_TitulosResumenes() {
        DefaultListModel<String> listModel = new DefaultListModel<>();

        Nodo<String> nodoTitulo = titulos.getFirst();
        for (int i = 0; i < titulos.getLenght(); i++) {
            listModel.addElement(nodoTitulo.getValor());//agrego
            nodoTitulo = nodoTitulo.getSiguiente();//se mueve

        }
        jList2.setModel(listModel);
    }*/

    public void Cargar_TitulosResumenes3() {
        Lista lista = new Lista();
        DefaultListModel<String> listModel = new DefaultListModel<>();

        
        Lista<String> titulosOrdenados = lista.obtenerTitulosOrdenados(titulos);

        Nodo<String> nodoTitulo = titulosOrdenados.getFirst();
        while (nodoTitulo != null) {
            listModel.addElement(nodoTitulo.getValor());
            nodoTitulo = nodoTitulo.getSiguiente();
        }
        jList2.setModel(listModel);
    }

    /*
    public void Cargar_TitulosResumenes2() {
        HashTable hashtable=new HashTable();
        DefaultListModel<String> listModel = new DefaultListModel<>();
        Nodo<String> nodoTitulo = titulos.getFirst();
        for (int i = 0; i < titulos.getLenght(); i++) {
            Lista<String> Listatitulosordenados=hashtable.obtenerTitulosOrdenados(nodoTitulo.getValor());
            Nodo<String> nodoTitulos=Listatitulosordenados.getFirst();
            
            for(int j=0;j<Listatitulosordenados.getLenght();j++){
                listModel.addElement(nodoTitulos.getValor());
                nodoTitulos=nodoTitulos.getSiguiente();
            }
            
            nodoTitulo = nodoTitulo.getSiguiente();
        }
        jList2.setModel(listModel);
    }*/

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        pizarra1.setText("");

        jList2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        String selectedValue = jList2.getSelectedValue();
        if (selectedValue != null) {
            Resumen resumen = Inicio.tabla.getResumen(selectedValue);
            String resumenStr = resumen.toString();
            WordCounter(selectedValue);//Frecuencia
            pizarra1.setText(resumenStr);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccionar un documento");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cargar_TitulosResumenes3();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea pizarra;
    private javax.swing.JTextArea pizarra1;
    // End of variables declaration//GEN-END:variables
}
