/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author VivianaPetit
 */
public class Menu extends javax.swing.JFrame {
    Fuentes tipoFuente;
    /**
     * Creates new form Ventana1
     */
    public Menu() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        tipoFuente = new Fuentes();
        jLabel8.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 20));
        jLabel5.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 20));
        jLabel6.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 20));
        jLabel7.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 20));
        jLabel9.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound2 = new Interfaz.PanelRound();
        panelRound1 = new Interfaz.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelRound3 = new Interfaz.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        panelRound4 = new Interfaz.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        panelRound5 = new Interfaz.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        panelRound6 = new Interfaz.PanelRound();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(213, 228, 207));
        panelRound2.setRoundBottomLeft(10);
        panelRound2.setRoundBottomRight(10);
        panelRound2.setRoundTopLeft(10);
        panelRound2.setRoundTopRight(10);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(2, 64, 83));
        panelRound1.setRoundBottomLeft(10);
        panelRound1.setRoundBottomRight(10);
        panelRound1.setRoundTopLeft(10);
        panelRound1.setRoundTopRight(10);
        panelRound1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound1MousePressed(evt);
            }
        });
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_key.png"))); // NOI18N
        jLabel5.setText("Buscar por Palabra Clave");
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 40));

        panelRound2.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 250, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono.png"))); // NOI18N
        panelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 70, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Metro mendeley.png"))); // NOI18N
        panelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono.png"))); // NOI18N
        panelRound2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 70, 270));

        panelRound3.setBackground(new java.awt.Color(2, 64, 83));
        panelRound3.setRoundBottomLeft(10);
        panelRound3.setRoundBottomRight(10);
        panelRound3.setRoundTopLeft(10);
        panelRound3.setRoundTopRight(10);
        panelRound3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound3MousePressed(evt);
            }
        });
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono lupa (2).png"))); // NOI18N
        jLabel8.setText("Analizar Resumen");
        panelRound3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, -1));

        panelRound2.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 250, 40));

        panelRound4.setBackground(new java.awt.Color(2, 64, 83));
        panelRound4.setRoundBottomLeft(10);
        panelRound4.setRoundBottomRight(10);
        panelRound4.setRoundTopLeft(10);
        panelRound4.setRoundTopRight(10);
        panelRound4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound4MousePressed(evt);
            }
        });
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_autor.png"))); // NOI18N
        jLabel6.setText("Buscar por Autor");
        panelRound4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        panelRound2.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 250, 40));

        panelRound5.setBackground(new java.awt.Color(2, 64, 83));
        panelRound5.setRoundBottomLeft(10);
        panelRound5.setRoundBottomRight(10);
        panelRound5.setRoundTopLeft(10);
        panelRound5.setRoundTopRight(10);
        panelRound5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound5MousePressed(evt);
            }
        });
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Metro mendeley (6).png"))); // NOI18N
        jLabel7.setText("Cargar Resumen");
        panelRound5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 40));

        panelRound2.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 250, 40));

        panelRound6.setBackground(new java.awt.Color(2, 64, 83));
        panelRound6.setRoundBottomLeft(10);
        panelRound6.setRoundBottomRight(10);
        panelRound6.setRoundTopLeft(10);
        panelRound6.setRoundTopRight(10);
        panelRound6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound6MousePressed(evt);
            }
        });
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-exit.png"))); // NOI18N
        jLabel9.setText("Salir");
        panelRound6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        panelRound2.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 250, 40));

        getContentPane().add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound5MousePressed
        CargarResumen v4 = new CargarResumen();
        this.setVisible(false);
        v4.setVisible(true);
    }//GEN-LAST:event_panelRound5MousePressed

    private void panelRound1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound1MousePressed
        BuscarPalabraClave v2 = new BuscarPalabraClave();
        this.setVisible(false);
        v2.setVisible(true);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_panelRound1MousePressed

    private void panelRound3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound3MousePressed
        // TODO add your handling code here:
        AnalizarResumenes v1 = new AnalizarResumenes();
        this.setVisible(false);
        v1.setVisible(true);
        this.setLocationRelativeTo(null);

    }//GEN-LAST:event_panelRound3MousePressed

    private void panelRound4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound4MousePressed
        BuscarPorAutor v3 = new BuscarPorAutor();
        this.setVisible(false);
        v3.setVisible(true);
    }//GEN-LAST:event_panelRound4MousePressed

    private void panelRound6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound6MousePressed
        JOptionPane.showMessageDialog(null, "¡Vuelve pronto!");
        System.exit(0);
    }//GEN-LAST:event_panelRound6MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private Interfaz.PanelRound panelRound1;
    private Interfaz.PanelRound panelRound2;
    private Interfaz.PanelRound panelRound3;
    private Interfaz.PanelRound panelRound4;
    private Interfaz.PanelRound panelRound5;
    private Interfaz.PanelRound panelRound6;
    // End of variables declaration//GEN-END:variables
}
