/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import java.io.*;
import javax.swing.JOptionPane;
import metromendeley.*;


/**
 *
 * @author VivianaPetit
 */
public class Ventana2 extends javax.swing.JFrame {
    public static Lista<Resumen> resumenes;
    public static Lista<String> rutas;
    public static HashTable tabla;

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
        resumenes = new Lista<>();
        rutas = new Lista<>();
        tabla = new HashTable();
    }

    public void crearResumenes(String ruta) {
        try {
            FileReader fr = new FileReader(ruta);
            BufferedReader br = new BufferedReader(fr);

            Resumen resumen;
            String titulo = "";
            Lista<String> autores = new Lista<>();
            String cuerpo = "";
            String palabrasClave = "";
            String linea;

            boolean aux = false;
            int contador = 0;
            while((linea = br.readLine()) != null){
                if (contador == 0){
                    titulo += linea;
                    contador ++;
                }
                else if (linea.contains("Autores")) {
                    aux = true;
                }
                else if (linea.contains("Resumen")){
                    cuerpo += br.readLine();
                    aux = false;
                }
                else if (aux) {
                    autores.insertFinal(linea);
                }
                else if (linea.startsWith("Palabras claves: ")){
                    palabrasClave += linea.replaceAll("Palabras claves: ", "");
                }
            }
            String[] palabrasDivididas = palabrasClave.split(",");
            Lista<String> palabrasClaves = new Lista();
            for (String palabra : palabrasDivididas) {
                palabrasClaves.insertFinal(palabra);
            }
            resumen = new Resumen(titulo, autores, cuerpo, palabrasClaves);

            resumenes.insertFinal(resumen);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void obtenerRutaArchivos(){
        Lista<String> nombreArchivos = new Lista<>();

        nombreArchivos.insertFinal("\\src\\Resumenes\\resumen1.txt");
        nombreArchivos.insertFinal("\\src\\Resumenes\\resumen2.txt");
        nombreArchivos.insertFinal("\\src\\Resumenes\\resumen3.txt");
        nombreArchivos.insertFinal("\\src\\Resumenes\\resumen4.txt");

        Nodo<String> nombre = nombreArchivos.getFirst();
        String rutaBaseProyecto = System.getProperty("user.dir");
        for (int i = 0; i < nombreArchivos.getLenght(); i++) {
            String rutaRelativa = nombre.getValor();
            String rutaAbsoluta = rutaBaseProyecto + File.separator + rutaRelativa;
            File archivo = new File(rutaAbsoluta);
            rutas.insertFinal(archivo.getAbsolutePath());
            nombre = nombre.getSiguiente();
        }
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("crear tabla hash");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButton1)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jButton1)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        obtenerRutaArchivos();
        Nodo<String> aux = rutas.getFirst();
        for (int i = 0; i < rutas.getLenght(); i++){
            crearResumenes(aux.getValor());
            aux = aux.getSiguiente();
        }
        Nodo<Resumen> nodoResumen = resumenes.getFirst();
        for (int i = 0; i<resumenes.getLenght(); i++) {
            tabla.insertar(nodoResumen.getValor());
            nodoResumen = nodoResumen.getSiguiente();
        }
        tabla.imprimir();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
